default:
  tags: [test]

stages:
  - build
  - style
  - tests
  - deploy

making:
  stage: build
  script:
    - cd src/cat/
    - make s21_cat
    - cd ../grep/
    - make s21_grep
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'failed' ]; then
        bash ./src/tg_bot_notify.sh 0
      fi
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

checking:
  stage: style
  script:
    - cd src/cat/
    - make check
    - cd ../grep/
    - make check
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'failed' ]; then
        bash ./src/tg_bot_notify.sh 0
      fi

testing:
  stage: tests
  script:
    - cd src/cat/
    - make test
    - cd ../grep/
    - make test
    - bash ./src/tg_bot_notify.sh 1
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'failed' ]; then
        bash ./src/tg_bot_notify.sh 0
      fi

deploy:
  stage: deploy
  dependencies:
    - making
  when: manual
  script:
    - bash ./src/cd_script.sh
    - bash ./src/tg_bot_notify.sh 1
  after_script:
    - >
      if [ $CI_JOB_STATUS == 'failed' ]; then
        bash ./src/tg_bot_notify.sh 3
      fi