default:
  tags: [test]

stages:
  - build
  - style
  - tests
  - deploy

making:
  stage: build
  script:
    - cd src/cat/
    - make s21_cat
    - cd ../grep/
    - make s21_grepp
    - cat ./src/status.txt << 1
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

ci_notify:
  stage: build
  script:
    - bash ./src/tg_bot_notify.sh 0
  when: on_failure

checking:
  stage: style
  script:
    - cd src/cat/
    - make check
    - cd ../grep/
    - make check
    - ./src/status.txt << 2

testing:
  stage: tests
  script:
    - cd src/cat/
    - make test
    - cd ../grep/
    - make test
    - ./src/status.txt << 3
    
# ci_notify:
#   stage: tests
#   script:
#     - bash ./src/tg_bot_notify.sh 1

deploy:
  stage: deploy
  dependencies:
    - making
  when: manual
  script:
    - bash ./src/cd_script.sh
    - ./src/status.txt << 4
    # - bash ./src/tg_bot_notify.sh
    - src/status.txt << 0


#   stage: deploy
#   script:
#     - bash ./src/tg_bot_notify.sh 2