default:
  tags: [test]

stages:
  - build
  - style

making:
  stage: build
  script:
    - cd src/cat/
    - make s21_cat
    - cd ../grep/
    - make s21_grep
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

checking:
  stage: style
  script:
    - cd src/cat/
    - make check
    - cd ../grep/
    - make check